import Head from "next/head";
import * as Space from "react-spaces";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Space.ViewPort id="viewport">
				<Space.LeftResizable id="left" size="25%" centerContent={Space.CenterType.HorizontalVertical} style={{ backgroundColor: "white" }}>
					<span style={{ color: "black" }}>Hello world</span>
				</Space.LeftResizable>
				<Space.Fill id="fill" centerContent={Space.CenterType.HorizontalVertical}>
					Hello world
				</Space.Fill>
			</Space.ViewPort>
		</>
	);
}
